siteek/myauth/urls.py
from django.contrib.auth.views import LoginView
from django.shortcuts import redirect

from .views import get_cookie_view, set_cookie_view, set_session_view, get_session_view, AboutMeView, RegisterView, logout_view, FooBarView, HelloView
from django.urls import path

app_name = 'myauth'

urlpatterns = [
    path('hello/', HelloView.as_view(), name='hello'),
    path('logout/', logout_view, name='logout'),
    path('login/', LoginView.as_view(template_name='myauth/login.html', redirect_authenticated_user=True), name='login'),
    path('cookie/get', get_cookie_view, name='cookie_get'),
    path('cookie/set', set_cookie_view, name='cookie_set'),
    path('session/set', set_session_view, name='session_set'),
    path('session/get', get_session_view, name='session_get'),
    path('about-me/', AboutMeView.as_view(), name='about-me'),
    path('register/', RegisterView.as_view(), name='register'),
    path('foo-bar/', FooBarView.as_view(), name='foo-bar'),

]

siteek/shopapp/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (ShopIndexView, GroupsListView, ProductsListView, OrdersListView, ProductDetailsView, OrderDetailsView,
                    ProductCreateView, ProductUpdateView, ProductDeleteView, ProductsDataExportView, ProductViewSet)
app_name = 'shopapp'
routers = DefaultRouter()
routers.register("products", ProductViewSet)
urlpatterns = [
    path('', ShopIndexView.as_view(), name='index'),
    path("api/", include(routers.urls)),
    path('groups/', GroupsListView.as_view(), name='groups_list'),
    path('products/', ProductsListView.as_view(), name='products_list'),
    path('products/export', ProductsDataExportView.as_view(), name='products-export'),
    path('products/create/', ProductCreateView.as_view(), name='create_product'),
    path('products/<int:pk>/', ProductDetailsView.as_view(), name='products_details'),
    path('products/<int:pk>/update', ProductUpdateView.as_view(), name='product_update'),
    path('products/<int:pk>/archive', ProductDeleteView.as_view(), name='product_delete'),
    path('orders/', OrdersListView.as_view(), name='orders_list'),
    path('orders/<int:pk>/', OrderDetailsView.as_view(), name='order_details'),
]

siteek/siteek/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.messages import api
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView, SpectacularRedocView
from .sitemaps import sitemaps

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('shop/', include('shopapp.urls')),
    path('myauth/', include('myauth.urls')),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger'),
    path('api/schema/redoc', SpectacularRedocView.as_view(), name='redoc'),
    path('api/', include('myapiapp.urls')),
    path('blog/', include('blogapp.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    path('myauth/', include('myauth.urls')),
    path('shop/', include('shopapp.urls')),
)

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )
    urlpatterns.extend(
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )

    urlpatterns.append(
        path('__debug__/', include('debug_toolbar.urls'))
    )

siteek/shopapp/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models import CharField


def product_preview_directory_path(instance: "Product", filename: str):
    return 'products/product_{pk}/preview/{filename}'.format(
        pk=instance.pk,
        filename=filename
    )


class Product(models.Model):
    """
    Модель Product представляет собой модель товара, который можно продавать

    Заказы тут :model:`shopapp.Order`.
    """
    class Meta:
        ordering = ['name', 'price']
        # db_table = 'tech_products'
        # verbose_name_plural = 'products'

    name = models.CharField(max_length=100, db_index=True)
    description = models.TextField(null=False, blank=True, db_index=True)
    price = models.DecimalField(default=0, max_digits=8, decimal_places=2)
    discount = models.SmallIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    archived = models.BooleanField(default=False)
    preview = models.ImageField(null=True, blank=True, upload_to=product_preview_directory_path)

    @property
    def description_short(self):
        if len(self.description) < 48:
            return self.description
        return self.description[:48] + '...'

    def __str__(self):
        return f'Product(pk={self.pk}, name={self.name!r})'


def product_images_directory_path(instance: 'ProductImage', filename: str):
    return 'products/product_images/{pk}/{filename}'.format(
        pk=instance.product.pk,
        filename=filename
    )


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to=product_images_directory_path)
    description = models.CharField(max_length=200, null=False, blank=True)


class Order(models.Model):
    delivery_address = models.TextField(null=True, blank=True)
    promocode = CharField(max_length=25, null=False, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    products = models.ManyToManyField(Product, related_name='orders')
    receipt = models.FileField(null=True, upload_to='orders/receipts')

siteek/shopapp/forms.py
from django.contrib.auth.models import Group
from django import forms
from shopapp.models import Product
from django.forms import ModelForm

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'price', 'description', 'discount', 'preview']

    # images = forms.ImageField(
    #     widget=forms.ClearableFileInput(attrs={'multiple': True}),
    # )



class GroupForm(ModelForm):
    class Meta:
        model = Group
        fields = ['name']

class CSVImportForm(forms.Form):
    csv_file = forms.FileField()

siteek/shopapp/views.py
"""
В этом модуле лежат различные наборы представления для интернет-магазина.

Разные view интернет магазина.
"""
import csv
from crypt import methods
from csv import DictWriter
from dataclasses import fields
from itertools import product
from lib2to3.fixes.fix_input import context
from timeit import default_timer
import logging
from django.core.cache import cache
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from rest_framework.decorators import action, parser_classes
from django.contrib.admin import action
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework.filters import SearchFilter, OrderingFilter
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import Group
from django.http import HttpResponse, HttpRequest, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, reverse, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from rest_framework.request import Request
from rest_framework.viewsets import ModelViewSet
from .models import Product, Order, ProductImage
from .forms import ProductForm
from django.views import View
from .forms import GroupForm
from .serializers import ProductSerializer
from drf_spectacular.utils import extend_schema, OpenApiResponse
from rest_framework.reverse import reverse
from rest_framework.decorators import action
from rest_framework.response import Response
from rest_framework.parsers import MultiPartParser, FormParser
from .common import save_csv_products

log = logging.getLogger(__name__)


@extend_schema(description='Product views CRUD')
class ProductViewSet(ModelViewSet):
    """
    Набор представлений для действий над Product
    Полный CRUD для сущностей товара
    """
    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    filter_backends = [
        SearchFilter,
        DjangoFilterBackend,
        OrderingFilter,
    ]
    search_fields = ['name', "description"]
    filterset_fields = [
        "name",
        "description",
        "price",
        "discount",
        "archived",
    ]
    ordering_fields = [
        "name",
        "price",
        "discount",
    ]

    @method_decorator(cache_page(60 * 2))
    def list(self, *args, **kwargs):
        print('Hello products list')
        return super().list(*args, **kwargs)

    @action(detail=False, methods=['get'])
    def download_csv(self, request: Request):
        response = HttpResponse(content_type='text/csv')
        filename = 'products-export.csv'
        response['Content-Disposition'] = f'attachment; filename={filename}'
        queryset = self.filter_queryset(self.get_queryset())
        fields = [
            'name',
            'description',
            'price',
            'discount',
        ]
        queryset = queryset.only(*fields)
        writer = DictWriter(response, fieldnames=fields)
        writer.writeheader()

        for product in queryset:
            writer.writerow(
                {
                    field: getattr(product, field)
                    for field in fields
                }
            )
        return response

    @action(detail=False, methods=['post'], parser_classes=[MultiPartParser], )
    def upload_csv(self, request: Request):
        products = save_csv_products(
            request.FILES['file'].file,
            encoding=request.encoding,
        )
        serializer = self.get_serializer(products, many=True)
        return Response(serializer.data)

    @extend_schema(summary='Get one product by id',
                   description='Retrieves **product**, return 404 if not found',
                   responses={
                       200: ProductSerializer,
                       404: OpenApiResponse(description='Empty response, product not found')})
    def retrieve(self, *args, **kwargs):
        return super().retrieve(*args, **kwargs)


class ShopIndexView(View):

    def get(self, request: HttpRequest):
        products = [
            ('Laptop', 1999),
            ('Desktop', 2999),
            ('Smartphone', 999),
        ]
        context = {
            'time_running': default_timer(),
            'products': products,
            'items': 5
        }
        log.debug('Products for shop index: %s', product)
        log.info('Rendering shop index')
        print('shop index context', context)
        return render(request, 'shopapp/shop-index.html', context=context)


class GroupsListView(View):
    def get(self, request: HttpRequest):
        context = {
            'form': GroupForm(),
            "groups": Group.objects.prefetch_related('permissions').all(),
        }
        return render(request, 'shopapp/groups-list.html', context=context)

    def post(self, request: HttpRequest):
        form = GroupForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect(request.path)


class ProductDetailsView(DetailView):
    template_name = 'shopapp/product-details.html'
    queryset = Product.objects.prefetch_related('images')
    context_object_name = 'product'


class ProductsListView(ListView):
    template_name = 'shopapp/products-list.html'
    # model = Product
    context_object_name = 'products'
    queryset = Product.objects.filter(archived=False)


class ProductCreateView(UserPassesTestMixin, CreateView):
    def test_func(self):
        return self.request.user.is_superuser

    model = Product
    fields = 'name', 'price', 'description', 'discount', 'preview'
    success_url = reverse_lazy('shopapp:products_list')


class ProductUpdateView(UpdateView):
    model = Product
    template_name_suffix = '_update_form'
    form_class = ProductForm

    def get_success_url(self):
        return reverse('shopapp:products_details', kwargs={'pk': self.object.pk})

    def form_valid(self, form):
        response = super().form_valid(form)
        for image in form.files.getlist('images'):
            ProductImage.objects.create(
                product=self.object,
                image=image,
            )
        return response


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy('shopapp:products_list')

    def form_valid(self, form):
        success_url = self.get_success_url()
        self.object.archived = True
        self.object.save()
        return HttpResponseRedirect(success_url)


class OrdersListView(LoginRequiredMixin, ListView):
    queryset = (
        Order.objects
        # .select_related('user').
        # prefetch_related('products')
        .all()
    )


class OrderDetailsView(PermissionRequiredMixin, DetailView):
    permission_required = 'shopapp.view_order'
    queryset = (Order.objects.select_related('user').prefetch_related('products'))


class ProductsDataExportView(View):
    def get(self, request: HttpRequest):
        cache_key = 'products-data-export'
        products_data = cache.get(cache_key)
        if products_data is None:
            products = Product.objects.order_by('pk').all()
            products_data = [
                {
                    'pk': product.pk,
                    'name': product.name,
                    'price': product.price,
                    'archived': product.archived,
                }
                for product in products
            ]
            cache.set(cache_key, products_data, 300)
            elem = products_data[0]
            name = elem['name']
            print("name: ", name)
        return JsonResponse({'products': products_data})

siteek/shopapp/templates/shopapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}
      Base Title
      {% endblock %}
    </title>
</head>
<body>
{% block body %}
BASE BODY
      {% endblock %}

<div>
  {% now 'H:i' %}
</div>
<div>
  {% now 'l' as current_weekday %}
  Today is {{current_weekday}}
</div>
</body>
</html>

siteek/shopapp/templates/shopapp/create-product.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Create product
{% endblock %}

{% block body %}
    <h1>Create product</h1>
    <div>
    <form method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create</button>
    </form>
    </div>
    <div>
    <a href="{% url 'shopapp:products_list' %}">Go to products list</a>
    </div>
{% endblock %}

siteek/shopapp/templates/shopapp/groups-list.html
{% extends 'shopapp/base.html' %}
{% block title %} 
    Groups List
{% endblock %}

{% block body %}
<h1>Groups</h1>
    <div>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create</button>
    </form>
    </div>
    <div>
        {% if not groups %}
            <h3>No groups yet</h3>
        {% else %}
        <ul>
            {% for group in groups %}
                <li>
                    <div>{{ group.name }}</div>
                    <ul>
                        {% for permission in group.permissions.all %}
                            <li>
                                {{ permission.name }}
                                (<code> {{ permission.codename }} </code>)
                            </li>
                        {% endfor %}
                    </ul>
                </li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
{% endblock %}

siteek/shopapp/templates/shopapp/order_detail.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Order № {{ object.pk }} details
{% endblock %}

{% block body %}
    <h1>Order № {{ object.pk }} </h1>
        <div>
        <p>Ordered by: {% firstof object.user.firstname object.user.username %}</p>
        <p>Promocode: {{ object.promocode }}</p>
        <p>Delivery address: {{ object.delivery_address }}</p>
            <div>
                Product in order:
            </div>
            <ul>
                {% for product in object.products.all %}
                <li>{{ product.name }} for {{ product.price }}</li>
                {% endfor %}
            </ul>
        </div>
    <div>
    <a href="{% url 'shopapp:orders_list' %}"> Back to orders</a>
    </div>
{% endblock %}

siteek/shopapp/templates/shopapp/order_list.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Orders list
{% endblock %}

{% block body %}
    <h1>Orders:</h1>
    {% if object_list %}
        <div>
            {% for order in object_list %}
        <div>
        <a href="{% url 'shopapp:order_details' pk=order.pk %}">Details №{{ order.pk }}</a>
        <p>Name: {% firstof order.user.firstname order.user.username %}</p>
        <p>Promocode: {{ order.promocode }}</p>
        <p>Delivery address: {{ order.delivery_address }}</p>
            <div>
                Product in order:
            </div>
            <ul>
                {% for product in order.products.all %}
                <li>{{ product.name }} for {{ product.price }}</li>
                {% endfor %}
            </ul>
        </div>
        {% endfor %}
        </div>
    {% else %}

    <h3>No products yet</h3>
    {% endif %}
{% endblock %}

siteek/shopapp/templates/shopapp/product-details.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Product №{{ product.pk }}
{% endblock %}

{% block body %}
    <h1>Product <strong>{{ product.name }}</strong></h1>
    <div>
    <div>Description: <em>{{ product.description }}</em></div>
    <div>Price: {{ product.price }}</div>
    <div>Discount: {{ product.discount }}</div>
    <div>Archived: {{ product.archived }}</div>
    {% if product.preview %}
    <img src="{{ product.preview.url }}" alt="{{ product.preview.name }}">
    {% endif %}
    <h3>Images:</h3>
    <div>
    {% for img in product.images.all %}
        <div>
            <img src="{{ img.image.url }}" alt="{{ img.description }}">
            <p>{{ img.description }}</p>
        </div>
    {% empty %}
        <p>No images uploaded yet</p>
    {% endfor %}
    </div>
    </div>
    <div>
    <a href="{% url 'shopapp:product_update' pk=product.pk %}">Update product</a>
    </div>
    <div>
    <a href="{% url 'shopapp:product_delete' pk=product.pk %}">Archive product</a>
    </div>
    <div>
    <a href="{% url 'shopapp:products_list' %}">Back to products list</a>
    </div>

{% endblock %}

siteek/shopapp/templates/shopapp/product_confirm_delete.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Confirm Archived {{ object.name }}
{% endblock %}

{% block body %}
    <h1>Are you sure you want to archive {{ object.name }}</h1>
    <br>
    <div>
    <a href="{% url 'shopapp:products_details' pk=object.pk %}">Back to product</a>
    </div>
    <br>
    <div>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Archive</button>
    </form>
    </div>
{% endblock %}

siteek/shopapp/templates/shopapp/product_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Create product
{% endblock %}

{% block body %}
    <h1>Create product</h1>
    <div>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create</button>
    </form>
    </div>
    <div>
    <a href="{% url 'shopapp:products_list' %}">Back to products list</a>
    </div>
{% endblock %}

siteek/shopapp/templates/shopapp/product_update_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Update product
{% endblock %}

{% block body %}
    <h1>Update product</h1>
    <div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <label for="images">Images:</label>
            <input type="file" name="images" multiple>
            <button type="submit">Update</button>
        </form>
    </div>
    <div>
        <a href="{% url 'shopapp:products_details' pk=object.pk %}">Back to product № {{ object.pk }}</a>
    </div>
{% endblock %}

siteek/shopapp/templates/shopapp/products-list.html
{% extends 'shopapp/base.html' %}

{% load i18n %}

{% block title %}
    {% translate 'Product list' %}
{% endblock %}

{% block body %}
    <h1>{% translate 'Products' %}:</h1>
    {% if products %}

        <div>
        {% blocktranslate count products_count=products|length %}
            There is only one product
            {% plural %}
            There are {{ products_count }} products
        {% endblocktranslate %}
        </div>

        <div>
            {% for product in products %}
        <div>
        <p><a href="{% url 'shopapp:products_details' pk=product.pk %}">{% translate 'Name' %}: {{ product.name }}</a></p>
        <p>{% translate 'Price' %}: {{ product.price }}</p>
        {% translate 'no discount' as no_discount%}
        <p>{% translate 'Discount' %}: {% firstof product.discount no_discount %}</p>

        {% if product.preview %}
            <img src="{{ product.preview.url }}" alt="{{ product.preview.name }}">
        {% endif %}
        </div>
        {% endfor %}
        </div>

        <div>
            <a href="{% url 'shopapp:create_product' %}" >{% translate 'Create a new product' %}</a>
        </div>
        {% else %}
        {% url 'shopapp:product_create' as create_product_url %}
        {% blocktranslate %}
        <h3>No products yet</h3>
        <a href="{{ create_product_url }}">Create a new one</a>
        {% endblocktranslate %}
    {% endif %}
    {% endblock %}

siteek/shopapp/templates/shopapp/products_changelist.html
{% extends 'admin/change_list.html' %}
{% load admin_urls %}

{% block object-tools-items %}
	<li>
    <a href="{% url 'admin:import_products_csv' %}" class="addlink">Import CSV</a>
    </li>
    {{ block.super }}
{% endblock %}s

siteek/shopapp/templates/shopapp/shop-index.html
{% extends 'shopapp/base.html' %}

{% load cache %}

{% block title %}
    shop INDEX
{% endblock %}

{% block body %}
<h1>Hello, SHOP INDEX!</h1>
<div>
<ul>
    {% for name, price in products %}
    <li>
        {{ name }} ({{ name|length }}) for ${{ price }}
    </li>
    {% if name|length == 7 %}
    <span> Lucky product</span>
    {% endif %}
    {% empty %}
        No products here
    {% endfor %}
</ul>
</div>
    <div>
    <strong>
        You have {{ items }} cherr{{ items|pluralize:'y,ies' }}
    </strong>
    </div>
<div>
    Time running: {{time_running}}
</div>
    {% cache 100 lorem products %}

<div>
    {% lorem 3 p random %}
</div>
    {% endcache %}
{% endblock %}